### ISSUE TITLE
The Beast Within not providing full CC immunity to the hunter

### ISSUE THREAD

**Issue by caccavale** [watchyoursixx/hunter-tbc#49] opened 2021-03-30 16:24 UTC
TBW currently does not provide immunity to incapacitations or disorients in the current beta build: https://streamable.com/gxrymc

![image](https://user-images.githubusercontent.com/6198074/113022445-9e0e1180-9152-11eb-93f3-318aa56ec762.png)

Wowhead DB seems to indicated that as it is in game right now, its just immunity to stuns: 
https://tbc.wowhead.com/spell=34471/the-beast-within
![image](https://user-images.githubusercontent.com/6198074/113024101-5c7e6600-9154-11eb-817c-aeee23c9035a.png)

**Comment by Aggrend** [comment] 2021-03-31 16:30
This should be resolved as of the most recent build on beta. Let me know if it's not.

**Comment by watchyoursixx** [comment] 2021-04-02 08:32
https://www.twitch.tv/videos/972346248 made a short stream of this. @Aggrend 

Gouge still works on the hunter, as well as sap and blind.

**Comment by watchyoursixx** [comment] 2021-04-13 05:20
Commenting again, looks like Death coil is still being applied as well.

**Comment by Aggrend** [comment] 2021-04-13 17:21
The remaining cases should also be resolved in the next beta build (week of 4/19).

**Comment by watchyoursixx** [comment] 2021-04-20 01:11
confirmed all known CCs not working are now immune as of build 38364

**Closed as completed by watchyoursixx** 2021-04-20 01:11 UTC
Labels: bug, confirmed
