### ISSUE TITLE
Serpent Sting damage dealt with lower ranks not being properly increased by 10% of RAP (some scaling assumed here)

### ISSUE THREAD

**Issue by HunterNewt** [watchyoursixx/hunter-tbc#46] opened 2021-03-29 18:14 UTC
I'm not the greatest with calculations, but there's something funky going on here.
At first glance this seems to be working properly for Explosive Trap (although the initial damage doesn't seem to reflect the tooltip), the damage is still increased when popping Blood Fury + Earthstrike.
The other two abilities don't seem to be working properly.

**Comment by watchyoursixx** [comment] 2021-03-29 21:16
Duplicate of #16 

Will test later to figure it out exactly.

**Comment by watchyoursixx** [comment] 2021-04-03 00:22
Leaving this as a separate issue because I've confirmed that Serpent Sting and Explosive Trap are bugged.

Untalented RAP = 752

Rank 1 Explosive Trap = 100 - 130 damage
Expected Damage = (100 + 0.1 * 752) to (130 + 0.1 * 752) or 175 to 205
Actual Damage = 156 - 187
![image](https://user-images.githubusercontent.com/47162044/113462857-02e69780-93f1-11eb-86af-26f35f241674.png)


Rank 9 Serpent Sting = 111 per tick, 555 total damage
Expected Damage = (111 * 5 + 0.1 * 752) total, or 126 per tick
Actual Damage = 112 - 113
![image](https://user-images.githubusercontent.com/47162044/113462903-24e01a00-93f1-11eb-9141-319090339a5f.png)


Conclusions:
Explosive trap seems to be using around 7.5% of RAP instead of 10%
Serpent Sting appears to be using 1% of RAP instead of 10%
10% is expected based on patch 2.3 patch notes.
Immolation trap is behaving correctly and applying 10% of the hunter's RAP.

**Comment by HunterNewt** [comment] 2021-04-03 09:13
Quick question about immolation trap.
What is the reason for the tooltip damage not matching the actual damage happening?

With no gear or hawk (269 RAP), the rank 6 tooltip indicates 1012 damage, but my trap is doing 1030-1035 total damage.
With full gear, T3 4pc, and hawk (1459 RAP), the tooltip says 1264 damage, and my trap does 1150-1155 total damage.

**Comment by watchyoursixx** [comment] 2021-04-03 10:04
It appears all tooltips are incorrect that calculate damage on all classes

**Comment by watchyoursixx** [comment] 2021-04-13 05:36
tested again with new build and new rank (10)

Rank 10 serpent sting appears to be correct, but any rank below that is only gaining 1-2 damage.

**Comment by watchyoursixx** [comment] 2021-04-29 00:43
After further testing - it appears max rank of both abilities is working correctly.

I don't know what the scaling is below max rank, but explosive trap if it has reduced scaling for lower ranks, seems to be correct. Serpent sting however, appears still bugged because just 1 rank lower goes from 10% to 1% increase, along with the rest of the ranks.

**Comment by Aggrend** [comment] 2021-05-03 17:23
I spent quite a bit of time digging into this over the weekend and this actually behaves identical to reference, down to the tooltips displaying the wrong information on ranks below max rank. Max ranks function properly and get the full RAP benefit, but lower ranks do not. After some additional digging this seems to have been a by-product of the changes to spell downranking that went in during original TBC. 

This might have been considered a bug at the time, but for now I'm calling this NAB, as it perfectly matches reference.

**Comment by watchyoursixx** [comment] 2021-05-03 17:28
Closing, thanks for the comment!

**Closed as completed** 2021-05-03 17:28 UTC
Labels: bug, major
